default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gallagher-api_development

test:
  <<: *default
  database: gallagher-api_test

production:
  <<: *default
  database: gallagher-api_production
  username: gallagher-api
  password: <%= ENV['GALLAGHER-API_DATABASE_PASSWORD'] %>
